---
- hosts: client
  become: true
  vars:
    password: labas
  tasks:
    # Install Google Chrome and creates new user for its usage
   - name: Install Google Chrome from internet
     apt: 
       deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    
    # In order for password to work "passlib" has to be installed 
   - name: Create new user for Chrome usage 
     user:
       name: client
       password: "{{ password|password_hash('sha512') }}"
  
